---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: i want to install web server (apt-get install apache2)
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
      # state: absent (if u want to un-install the apache2 webserver)
    - name: i want to start webserver on debian nodes (service apache2 start)
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"
    - name: i want to install webserv on radhat nodes(service httpd start)

      service:
        name: https
        state: started
      when: ansible_os_family == "Redhat"


        